### ISSUE TITLE
Unit testing broken in travis-ci

### ISSUE THREAD

**Issue by jim-parry** [bcit-ci/CodeIgniter4#1003]
Several things have happened over the last 8 PR merges or so, breaking travis-ci. The unit tests are failing, but travis-ci is reporting "success".

PR 981 passed (1836 tests)
PR 984 LoggerTest failed (1 of 1837 tests) - not changed in this PR
PR 986 no change
PR 990 no change, except for more Javascript in front of tests
PR 993 travis-ci "breaks"
- "yarn" command not found
- 1.5 pages of "failed to fetch" errors"
- 8 failures on row two of tests
- "reset($vars) and more javascript on row after test 1098 ... system/Common.php:965
- phpunit exits without completing, reports success
- unclear if LoggerTest still fails or even runs
PR 995 travis-ci "breaks" more
- half page of gpg errors
- 10 failures now, on rows 2 & 3 of tests
- phpunit exits without completing, tracis reports success
PR 996 no change
- still broken, same errors but success reported
PR 998 no change

**Comment by jim-parry** [comment]
Hmmm - PR 993, where things first started to go south, seems to be the develop branch to me. :-/
https://github.com/bcit-ci/CodeIgniter4/pull/993 ... and follow the link to the travis-ci details.

**Comment by lonnieezell** [comment]
Oh, I see what you mean now. Well - I just got all of the tests for my exceptions branch working, so I'll be merging that here shortly and we'll see what it looks like after that.

I know I fixed a stray `dd()` call a couple of nights ago. Thought I did it in the develop branch, but guess not.

**Comment by lonnieezell** [comment]
Yup. that seemed to fix everything. Closing this.

**Comment by jim-parry** [comment]
Er, it didn't fix everything. 
I get ...
_PHP Fatal error:  Cannot declare class CodeIgniter\Exceptions\EmergencyError, because the name is already in use in /pub7/htdocs/CodeIgniter4/system/Exceptions/Error.php on line 9_
and I see that system/Exceptions/Error.php declares the class EmergencyError.
Yes, this is in the current develop branch of the repo :(

**Comment by lonnieezell** [comment]
Strange that doesn't show up locally or on Travis. :(

Renaming that class to simply Error is fine, and as it should be.
