### ISSUE TITLE
Problem throw error for default controller

### ISSUE THREAD

**Issue by arma7x** [bcit-ci/CodeIgniter4#146]
1) Problem for routing without using namespace:
case-1 = **$routes->add('', 'Home::index')** $this->controller has value of Home, result OK
case-2 = **$routes->add('/', 'Home::index')** $this->controller has value of \Home, result ErrorException line 500
2) Problem for routing with namespace
case-1 = **$routes->add('/', 'Home::index', ['namespace'=>'App\Controllers'])** $this->controller has value of \App\Controllers\Home, result ErrorException line 500

**What does line 500 really do in /system/Controller.php.**

**Comment by lonnieezell** [comment]
There is no line 500 in system/Controller. I'm going to guess that was actually in system/CodeIgniter.php, since that area has to do with booting the controller up.

With the very latest code, I'm not getting any errors during these scenarios, but I did fix one or two smaller issues with routing last night, so that might be why. 

Can you try again with the latest code and see if you're still getting the same issue?

**Comment by arma7x** [comment]
Ye, that was actually in system/CodeIgniter.php line 500 ;
include APPPATH.'Controllers/'.$this->router->directory().$this->controller.'.php';
I have latest code from github and still have this problem.

**Comment by lonnieezell** [comment]
I just made another push that, on my system, allows me to auto-route with or without namespaces. Can you check yours? 

If it doesn't work, please provide details on your server, OS, etc.

**Comment by arma7x** [comment]
Linux i686 Lubuntu 16.04, php 7.0.4 and Codeigniter4(branch::develop)

**ErrorException
include(/home/xxxxx/CodeIgniter4/application/Controllers/\App\Controllers\Home.php): failed to open stream: No such file or directory**

**Comment by lonnieezell** [comment]
Hm. Could you describe your app setup in detail? Here's mine, which should match the defaults currently: 

* Routes.php - defaultNamespace = 'App\Controllers'
* Routes.php - autoRoute = true
* Routes.php - $routes->add('/', 'Home::index');
* Home Controller - namespace = App\Controllers
* .htaccess file in place.
* Accessing /, /home, or /home/index all work for me

**Comment by lonnieezell** [comment]
Oh - and what file/line is giving that error now?

**Comment by arma7x** [comment]
Its solve now, changes commit [60effd6](https://github.com/bcit-ci/CodeIgniter4/commit/60effd6d6e62d6764e938f5d2ab6369400df943d) have fixed this issues, Thanks a lot.
Did latest commit allow controller under subfolder works without using namespace?
I get new error if route to controller that does not exist like http://127.0.0.1:2000/blog it should trigger 404 but again throw error exception:
ErrorException
include(/home/xxxxx/CodeIgniter4/application/Controllers/Sub.php): failed to open stream: No such file or directory

**Comment by lonnieezell** [comment]
Non-namespaced auto-routing in sub-folders should be working now, yes. 

Good point about the non-existing controllers. I was so focused on getting everything else to work, I forgot a basic check to see if the file existed first. Doh!

**Comment by arma7x** [comment]
**Non-namespaced** auto-routing in sub-folders still not works. In method autoRoute(), line 405, $this->directory does not determine the directory of specific file. Before set first segment to be the controller, I think it should determine whether the first segment is sub-folder or controller;
http://127.0.0.1:2000/home does return Home as controller -> OK
http://127.0.0.1:2000/home/index does return Home as controller -> OK
http://127.0.0.1:2000/subfolder/home does return Subfolder as controller -> 404
http://127.0.0.1:2000/subfolder/home/index does return Subfolder as controller -> 404

**Comment by arma7x** [comment]
**Non-namespaced** auto-routing in sub-folders still not works. In method autoRoute(), line 405, $this->directory does not determine the directory of specific file. Before set first segment to be the controller, I think it should determine whether the first segment is sub-folder or controller;
http://127.0.0.1:2000/home does return Home as controller -> OK
http://127.0.0.1:2000/home/index does return Home as controller -> OK
http://127.0.0.1:2000/subfolder/home does return Subfolder as controller -> 404
http://127.0.0.1:2000/subfolder/home/index does return Subfolder as controller -> 404

**Comment by arma7x** [comment]
In method validateRequest(), line 444 :
is_dir(APPPATH.'Controllers/'.$this->directory.$segments[0]) 
The $segments[0] should be ucfirst($segments[0]) for linux os, or else will return false.
I change those, and auto-routing in sub-folders seem works.

**Comment by lonnieezell** [comment]
Good catch. Fixed in 3562895051791707da9d681cefbff5ea73eb4170
