### ISSUE TITLE
Exception or disable toolbar for specific URI 

### ISSUE THREAD

**Issue by mixinix** [bcit-ci/CodeIgniter4#195]
I have tried 'filter' and used 'except' key for URI, but not working.

```
	public $globals = [
        'before' => [
            //'csrf'
            'auth'
        ],
        'after'  => [
            'toolbar' => ['except' => 'source/*']
        ]
    ];

```

And I gotten an error:

    ErrorException
    
        array_key_exists(): The first argument should be either a string or an integer

    BASEPATH/Filters\Filters.php at line 69

Is there any suggestion?

I think that is only for development mode.

**Comment by lonnieezell** [comment]
I won't have a chance to really look at it until later tonight, but I believe you need the value of 'except' to be an array:

```
'after'  => [
    'toolbar' => ['except' => ['source/*']]
]
```

I should probably have that attempt to do an auto-conversion to array if a string is found, though, since I can see that being a common error point.

**Comment by mixinix** [comment]
> 
    'after'  => [
        'toolbar' => ['except' => ['source/*']]
    ]

Still getting an error.

Example in this case:

I have a controller to send output as JavaScript's content (to minify it on the fly).

```
class Source extends Controller {
    
    public function js($encFile = '')
    {
        $output = @file_get_contents(WRITEPATH ."scripts/{$encFile}.js");
        // ...
        $response->send();
    }
    
}

```

The problem is when debug bar activate, the output included debug bar.

    //ci4play.dev/source/js/whateverscript.js

```
    function myscript(){//....}
    
    // debug bar output HTML
    // .....
    
```

I think the exception of toolbar is very useful to avoid collisions with other template.

**Comment by lonnieezell** [comment]
Should be working now, but let me know if you still run into problems.

**Comment by mixinix** [comment]
Haha.. Its working now! Thank you. :)

**Comment by mixinix** [comment]
Ooops!

```
public $globals = [
    'after'  => [
        'toolbar' => ['except' => ['test/*']]
    ]
];
```

The toolbar is still shown when I accessed the only controller of URI (without method, second of URI segment), like this:

    ci4play.dev/test

It's ok (toolbar is hidden):

    ci4play.dev/test/index

What do you think? I've not done with other services or filters.

Thanks. :)

**Comment by Fabio-Zeus-Soft** [comment]
Is it possible that this issue is back? 
My code:
```
'after' => [
            'pagecache',        // Web Page Caching
            'performance',      // Performance Metrics
            'toolbar' => [      // Debug Toolbar
                'except' => ['challenge']
            ]
        ],
```
Still getting: `TypeError: array_key_exists(): Argument #1 ($key) must be a valid array offset type`

**Comment by kenjis** [comment]
Use $global filter, instead of $required.
See https://codeigniter4.github.io/CodeIgniter4/incoming/filters.html#globals

**Comment by EmbDclic** [comment]
It seems very counterintuitive to move 'toolbar' from the new $required to $globals. I think it would be good to specify this in the documentation if 'except' is not supported for the required filters.

**Comment by kenjis** [comment]
Read https://codeigniter4.github.io/CodeIgniter4/incoming/filters.html#required
There is no `except`.
