### ISSUE TITLE
file upload issue

### ISSUE THREAD

**Issue by chistel** [bcit-ci/CodeIgniter4#591]
there seems to be an issue with file upload
here is the rules 'event_image'         => 'uploaded[event_image]|max_size[event_image,3000]|ext_in[event_image,png,jpg,gif]',

is selected a valid image, but i still got "event_image does not have a valid file extension."

also attempting file upload without validation is another issue, after upload and var_dumped, i get the response below
`object(CodeIgniter\HTTP\Files\UploadedFile)#80 (9) {
  ["path":protected]=>
  string(50) "C:\xampp\htdocs\eventulize\public\static/eventimg/"
  ["originalName":protected]=>
  string(40) "7cb0f576-aa96-4ffd-9828-b05078e0b084.jpg"
  ["name":protected]=>
  string(47) "event_image-1499359862_5091b58ce0ada0d6bbbe.tmp"
  ["originalMimeType":protected]=>
  string(10) "image/jpeg"
  ["error":protected]=>
  int(0)
  ["hasMoved":protected]=>
  bool(true)
  ["size":protected]=>
  int(145979)
  ["pathName":"SplFileInfo":private]=>
  string(24) "C:\xampp\tmp\php1413.tmp"
  ["fileName":"SplFileInfo":private]=>
  string(11) "php1413.tmp"
}`

this `event_image-1499359862_5091b58ce0ada0d6bbbe.tmp` is supposed to be `event_image-1499359862_5091b58ce0ada0d6bbbe.jpg` i used the `$file->getClientExtension()` function, but returns empty

**Comment by lonnieezell** [comment]
There was an issue with file extensions for uploaded files that should be fixed now. Please download the latest code and let me know if that fixes it for you.

**Comment by chistel** [comment]
yea worked. Sorry am going after each library piece by piece, observed the image library is still not stable, the base hander does not resize, the imagemagick handler says image process failed on line 164 in the imageMagickHandler

**Comment by lonnieezell** [comment]
No problem. And that's a good thing :) 

If you've found issues with the image library, please open additional issues for those with as much detail as you can provide about both your environment and what you tried/got.
